// <auto-generated />
namespace SensenbrennerHospital.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedaplicationuserkeytodonation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedaplicationuserkeytodonation));
        
        string IMigrationMetadata.Id
        {
            get { return "202104142342352_added aplication user key to donation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
