// <auto-generated />
namespace SensenbrennerHospital.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateddonationvolunteer04082021821 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateddonationvolunteer04082021821));
        
        string IMigrationMetadata.Id
        {
            get { return "202104090021131_updateddonationvolunteer04082021821"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
